# Generated by Django 3.1.2 on 2020-10-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('title_of_courtesy', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('extension', models.CharField(blank=True, max_length=4, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('reports_to', models.ForeignKey(blank=True, db_column='reports_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employees')),
            ],
            options={
                'verbose_name': 'employees',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='UsStates',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state_region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'us_states',
                'verbose_name_plural': 'us_states',
                'db_table': 'us_states',
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('territory_description', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.region')),
            ],
            options={
                'verbose_name': 'territories',
                'verbose_name_plural': 'territories',
                'db_table': 'territories',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritories',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='employee.employees')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.territories')),
            ],
            options={
                'verbose_name': 'employee_territories',
                'verbose_name_plural': 'employee_territories',
                'db_table': 'employee_territories',
                'unique_together': {('employee', 'territory')},
            },
        ),
    ]
