# Generated by Django 3.1.2 on 2020-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201118_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usstates',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
