# Generated by Django 3.1.2 on 2020-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'order details', 'verbose_name_plural': 'order details'},
        ),
    ]
